name: mister_chef
description: "APP de optimización de rutas para la empresa Mister Chef."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.0
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  url_launcher: ^6.3.0
  http: ^1.2.1
  flutter_polyline_points: ^2.1.0
  google_fonts: ^6.1.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
  
    